version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: carDB
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=car_sale_db
      - PGDATA=/data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped  
    networks:
      - webapi_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin  
    ports:
      - "8090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: Parsa@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - webapi_network
  redis:
    image: redis:latest
    container_name: redis_container
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - webapi_network
volumes:
  postgres:
  pgadmin:
  redis:
  logs:

networks:
  webapi_network:
    driver: bridge
